//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovori
    {
        public long id_Dogovor { get; set; }
        public long id_rabotadatel { get; set; }
        public long id_Uslugi { get; set; }
        public System.DateTime data_zakluchenite { get; set; }
    
        public virtual rabotadatel rabotadatel { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
