//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bazaEntities : DbContext
    {
        public bazaEntities()
            : base("name=bazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authorization> authorization { get; set; }
        public virtual DbSet<Dogovori> Dogovori { get; set; }
        public virtual DbSet<Dolzhnost> Dolzhnost { get; set; }
        public virtual DbSet<itog_sobesedovanie> itog_sobesedovanie { get; set; }
        public virtual DbSet<Otklki_Soskateley> Otklki_Soskateley { get; set; }
        public virtual DbSet<Predlozhenie_o_rabote> Predlozhenie_o_rabote { get; set; }
        public virtual DbSet<rabotadatel> rabotadatel { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<Sobesedovanie> Sobesedovanie { get; set; }
        public virtual DbSet<soiskateli> soiskateli { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
        public virtual DbSet<Vakansi> Vakansi { get; set; }
        public virtual DbSet<zayavki_rabotadateley> zayavki_rabotadateley { get; set; }
    }
}
