//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otklki_Soskateley
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otklki_Soskateley()
        {
            this.Predlozhenie_o_rabote = new HashSet<Predlozhenie_o_rabote>();
            this.Sobesedovanie = new HashSet<Sobesedovanie>();
        }
    
        public long id_otklil { get; set; }
        public long id_soiskatel { get; set; }
        public long id_vakansi { get; set; }
        public long id_status { get; set; }
        public System.DateTime data_otklik { get; set; }
    
        public virtual soiskateli soiskateli { get; set; }
        public virtual status status { get; set; }
        public virtual Vakansi Vakansi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predlozhenie_o_rabote> Predlozhenie_o_rabote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sobesedovanie> Sobesedovanie { get; set; }
    }
}
