//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rabotadatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rabotadatel()
        {
            this.Dogovori = new HashSet<Dogovori>();
            this.Predlozhenie_o_rabote = new HashSet<Predlozhenie_o_rabote>();
            this.Predlozhenie_o_rabote1 = new HashSet<Predlozhenie_o_rabote>();
            this.Vakansi = new HashSet<Vakansi>();
            this.zayavki_rabotadateley = new HashSet<zayavki_rabotadateley>();
        }
    
        public long id_rabotadatel { get; set; }
        public string naimenovaine_company { get; set; }
        public string address { get; set; }
        public int kontaknie_danniw { get; set; }
        public string email { get; set; }
        public string Opisanie_kompani { get; set; }
        public string kontaknote_litso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovori> Dogovori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predlozhenie_o_rabote> Predlozhenie_o_rabote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predlozhenie_o_rabote> Predlozhenie_o_rabote1 { get; set; }
        public virtual rabotadatel rabotadatel1 { get; set; }
        public virtual rabotadatel rabotadatel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vakansi> Vakansi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zayavki_rabotadateley> zayavki_rabotadateley { get; set; }
    }
}
