//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soiskateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soiskateli()
        {
            this.Otklki_Soskateley = new HashSet<Otklki_Soskateley>();
        }
    
        public long id_soiskatel { get; set; }
        public string familiya { get; set; }
        public string Imya { get; set; }
        public string Othcestvo { get; set; }
        public System.DateTime data_rozhdenie { get; set; }
        public string address { get; set; }
        public int phone { get; set; }
        public string email { get; set; }
        public string Obrazavanie { get; set; }
        public string opit_Raboti { get; set; }
        public string navik { get; set; }
        public string dopolnitelnie_dannie { get; set; }
        public long id_authorization { get; set; }
    
        public virtual authorization authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otklki_Soskateley> Otklki_Soskateley { get; set; }
    }
}
