//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public long id_Sotrudnik { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string kontakti { get; set; }
        public string email { get; set; }
        public string pasportnie_dannie { get; set; }
        public decimal zarplata { get; set; }
        public long id_authorization { get; set; }
        public long id_dolzhnost { get; set; }
    
        public virtual authorization authorization { get; set; }
        public virtual Dolzhnost Dolzhnost { get; set; }
    }
}
