//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace цдовым.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zayavki_rabotadateley
    {
        public long id_zayavka { get; set; }
        public long id_usluga { get; set; }
        public long id_status { get; set; }
        public long id_rabotadateley { get; set; }
    
        public virtual rabotadatel rabotadatel { get; set; }
        public virtual status status { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
